# Generated by Django 5.2.1 on 2025-05-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_phone_number', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='facility_pics/')),
                ('open_location', models.CharField(max_length=50)),
                ('maps_location', models.URLField()),
                ('website', models.URLField()),
                ('rating', models.FloatField()),
            ],
        ),
    ]
