# Generated by Django 5.2.1 on 2025-10-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('contact_phone_number', models.CharField(max_length=50)),
                ('picture', models.ImageField(default='facility_pics/Default Facility Picture.png', upload_to='facility_pics/')),
                ('province', models.CharField(max_length=50)),
                ('open_location', models.CharField(max_length=50)),
                ('maps_location', models.URLField()),
                ('website', models.URLField()),
                ('rating', models.FloatField(default=3)),
            ],
        ),
    ]
