# Generated by Django 5.2.1 on 2025-05-15 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_userprofile_role_vendorprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_phone_number', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, default=None, null=True, upload_to='facility_pics/')),
                ('open_location', models.CharField(max_length=50)),
                ('maps_location', models.URLField()),
                ('website', models.URLField()),
                ('belonged_vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to='user.vendorprofile')),
            ],
        ),
    ]
