# Generated by Django 5.2.1 on 2025-05-31 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='picture',
            field=models.ImageField(default='facility_pics/Default Facility Picture.png', upload_to='facility_pics/'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='rating',
            field=models.FloatField(default=3),
        ),
    ]
