# Generated by Django 5.2.1 on 2025-08-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_alter_facility_picture_alter_facility_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
