# Generated by Django 5.2.1 on 2025-08-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0004_facility_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='province',
            field=models.CharField(default='Adana', max_length=50),
            preserve_default=False,
        ),
    ]
