# Generated by Django 5.2.1 on 2025-10-12 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captain', to='user.appuserprofile'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', to='user.appuserprofile'),
        ),
        migrations.AddField(
            model_name='teaminvite',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invites', to='user.appuserprofile'),
        ),
        migrations.AddField(
            model_name='teaminvite',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_invites', to='team.team'),
        ),
        migrations.AddField(
            model_name='teamjoinrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='user.appuserprofile'),
        ),
        migrations.AddField(
            model_name='teamjoinrequest',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_requests', to='team.team'),
        ),
    ]
