# Generated by Django 5.2.1 on 2025-06-06 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        ('user', '0002_remove_vendorprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='captain', to='user.appuserprofile'),
        ),
    ]
