# Generated by Django 5.2.1 on 2025-06-08 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_remove_teaminvite_receiver_teaminvite_created_at_and_more'),
        ('user', '0002_remove_vendorprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='member_positions',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='teaminvite',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invites', to='user.appuserprofile'),
        ),
    ]
