# Generated by Django 5.2.1 on 2025-06-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_team_member_positions_alter_teaminvite_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='member_positions',
            field=models.JSONField(default=list),
        ),
    ]
