# Generated by Django 5.2.1 on 2025-05-19 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('app_user', 'App User'), ('vendor', 'Vendor')], max_length=10)),
                ('full_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50, unique=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='AppUserProfile',
            fields=[
                ('baseprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.baseprofile')),
                ('birth_date', models.DateField()),
                ('profile_picture', models.ImageField(default='app_user_profile_pics/Default User Profile Male.png', upload_to='app_user_profile_pics/')),
                ('wallet_balance', models.IntegerField(default=0)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('friends', models.ManyToManyField(related_name='friends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('user.baseprofile',),
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('baseprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.baseprofile')),
                ('company_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('user.baseprofile',),
        ),
        migrations.CreateModel(
            name='UserSkillSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint_speed', models.IntegerField(default=50)),
                ('attack_position', models.IntegerField(default=50)),
                ('finishing', models.IntegerField(default=50)),
                ('shot_power', models.IntegerField(default=50)),
                ('vision', models.IntegerField(default=50)),
                ('short_pass', models.IntegerField(default=50)),
                ('long_pass', models.IntegerField(default=50)),
                ('agility', models.IntegerField(default=50)),
                ('ball_control', models.IntegerField(default=50)),
                ('dribble', models.IntegerField(default=50)),
                ('def_awareness', models.IntegerField(default=50)),
                ('interceptions', models.IntegerField(default=50)),
                ('stamina', models.IntegerField(default=50)),
                ('strength', models.IntegerField(default=50)),
                ('aggression', models.IntegerField(default=50)),
                ('user_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_set', to='user.appuserprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='user.appuserprofile')),
            ],
        ),
        migrations.AddField(
            model_name='appuserprofile',
            name='skills',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='user.userskillset'),
        ),
    ]
