# Generated by Django 5.2.1 on 2025-10-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseprofile',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
