# Generated by Django 5.2.1 on 2025-05-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='temp_otp',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
