# Generated by Django 5.2.1 on 2025-05-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorprofile',
            name='company_name',
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='profile_picture',
            field=models.ImageField(default='vendor_profile_pics/Default Vendor Profile.png', upload_to='vendor_profile_pics/'),
        ),
    ]
