# Generated by Django 5.2.1 on 2025-05-12 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskillset',
            name='user',
        ),
        migrations.AddField(
            model_name='userskillset',
            name='user_profile',
            field=models.OneToOneField(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skill_set', to='user.userprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='profile_pics/Default User Profile Male.png', upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='user.userskillset'),
            preserve_default=False,
        ),
    ]
