# Generated by Django 5.2.1 on 2025-10-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_baseprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
