# Generated by Django 5.2.1 on 2025-05-12 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userskillset_user_userskillset_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskillset',
            name='user_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_set', to='user.userprofile'),
        ),
    ]
