# Generated by Django 5.2.1 on 2025-09-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_vendorprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuserprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
