# Generated by Django 5.2.1 on 2025-10-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_vendorprofile_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskillset',
            name='aggression',
        ),
        migrations.AddField(
            model_name='userskillset',
            name='acceleration',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=3),
        ),
        migrations.AddField(
            model_name='userskillset',
            name='voter_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='agility',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='attack_position',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='ball_control',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='def_awareness',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='dribble',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='finishing',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='interceptions',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='long_pass',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='short_pass',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='shot_power',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='sprint_speed',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='stamina',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='strength',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='vision',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=3),
        ),
    ]
