# Generated by Django 5.2.1 on 2025-10-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_userskillset_aggression_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskillset',
            name='abo',
            field=models.IntegerField(default=50),
        ),
    ]
