# Generated by Django 5.2.1 on 2025-10-12 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userskillset_abo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskillset',
            name='abo',
        ),
    ]
