# Generated by Django 5.2.1 on 2025-10-12 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_userskillset_abo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskillset',
            name='user_profile',
        ),
        migrations.AlterField(
            model_name='appuserprofile',
            name='skills',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='user.userskillset'),
        ),
    ]
