# Generated by Django 5.2.1 on 2025-10-12 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_userskillset_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskillset',
            name='acceleration',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='agility',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='attack_position',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='ball_control',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='def_awareness',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='dribble',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='finishing',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='interceptions',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='long_pass',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='short_pass',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='shot_power',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='sprint_speed',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='stamina',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='strength',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userskillset',
            name='vision',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
        ),
    ]
