# Generated by Django 5.2.1 on 2025-08-08 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field', '0006_alter_field_belonged_facility'),
        ('team', '0006_alter_team_member_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'active'), ('payment', 'pending payment'), ('on_hold', 'on hold'), ('canceled', 'canceled'), ('review', 'review'), ('past', 'past')], max_length=20)),
                ('belonged_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
                ('reserved_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field.field')),
                ('reserved_hours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field.reservationhour')),
            ],
        ),
    ]
