# Generated by Django 5.2.1 on 2025-10-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('start_hour', models.IntegerField()),
                ('remaining_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_users', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'active'), ('payment', 'payment-pending'), ('review', 'review'), ('past', 'completed'), ('on_hold', 'on-hold'), ('cancelled', 'cancelled'), ('timeout', 'payment-timeout')], max_length=20)),
            ],
        ),
    ]
