# Generated by Django 5.2.1 on 2025-10-12 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('field', '0001_initial'),
        ('reservation', '0002_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='ower_players',
            field=models.ManyToManyField(related_name='owed_reservations', to='user.appuserprofile'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserved_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='field.field'),
        ),
    ]
