# Generated by Django 5.2.1 on 2025-08-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='remaining_cost',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_cost',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
