# Generated by Django 5.2.1 on 2025-10-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='review_pending_users',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
