# Generated by Django 5.2.1 on 2025-10-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation_review_pending_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('payment', 'payment-pending'), ('past', 'completed'), ('on_hold', 'on-hold'), ('cancelled', 'cancelled'), ('timeout', 'payment-timeout')], max_length=20),
        ),
    ]
