# Generated by Django 5.2.1 on 2025-08-27 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_reservation_remaining_cost_reservation_total_cost'),
        ('team', '0006_alter_team_member_positions'),
        ('user', '0002_remove_vendorprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='ower_players',
            field=models.ManyToManyField(related_name='owed_reservations', to='user.appuserprofile'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='belonged_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='team.team'),
        ),
    ]
