# Generated by Django 5.2.1 on 2025-10-13 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_field_deposit_fee'),
        ('reservation', '0005_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='selected_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation', to='field.reservationhour'),
        ),
    ]
