# Generated by Django 5.2.1 on 2025-09-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_reservation_ower_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='remaining_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
