# Generated by Django 5.2.1 on 2025-09-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_alter_reservation_remaining_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='paid_users',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('payment', 'pending payment'), ('review', 'review'), ('past', 'past'), ('on_hold', 'on hold'), ('canceled', 'canceled')], max_length=20),
        ),
    ]
