# Generated by Django 5.2.1 on 2025-10-13 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_field_deposit_fee'),
        ('reservation', '0006_reservation_selected_hour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='selected_hour',
        ),
        migrations.AddField(
            model_name='reservation',
            name='hour_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='field.reservationhour'),
        ),
    ]
