# Generated by Django 5.2.1 on 2025-09-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_reservation_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('payment', 'pending payment'), ('review', 'review'), ('past', 'past'), ('on_hold', 'on hold'), ('canceled', 'canceled'), ('timeout', 'payment timeout')], max_length=20),
        ),
    ]
