# Generated by Django 5.2.1 on 2025-10-12 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(default='field_pics/Default Field Picture.png', upload_to='field_pics')),
                ('schedule_hours', models.JSONField(default=dict)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('belonged_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='facility.facility')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_hour', models.TimeField()),
                ('is_reserved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_hours', to='field.field')),
            ],
        ),
    ]
