# Generated by Django 5.2.1 on 2025-10-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='deposit_fee',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
