# Generated by Django 5.2.1 on 2025-05-31 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_alter_facility_picture_alter_facility_rating'),
        ('field', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(default='field_pics/field.png', upload_to='field_pics')),
                ('belonged_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility', to='facility.facility')),
            ],
        ),
        migrations.DeleteModel(
            name='Fields',
        ),
    ]
