# Generated by Django 5.2.1 on 2025-05-31 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0002_field_delete_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_hour', models.TimeField()),
                ('is_reserved', models.BooleanField(default=False)),
                ('code', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.AddField(
            model_name='field',
            name='schedule_hours',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='field',
            name='picture',
            field=models.ImageField(default='field_pics/Default Field Picture.png', upload_to='field_pics'),
        ),
        migrations.AddField(
            model_name='reservationhour',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_hours', to='field.field'),
        ),
    ]
