# Generated by Django 5.2.1 on 2025-06-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0003_reservationhour_delete_schedule_field_schedule_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='schedule_hours',
            field=models.JSONField(default=dict),
        ),
    ]
