# Generated by Django 5.2.1 on 2025-08-07 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0004_facility_description'),
        ('field', '0005_reservationhour_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='belonged_facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='facility.facility'),
        ),
    ]
