# Generated by Django 5.2.1 on 2025-08-26 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('field', '0006_alter_field_belonged_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='default_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationhour',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
